# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bplatformofficial

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_19835410c467467496957d2910bc0c6b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_91274609167946b7bca2fddd41591825 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_19835410c467467496957d2910bc0c6b }}/bplatform:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bplatformofficial'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9679d3b320bb44ad8fc97371fc32851c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_19835410c467467496957d2910bc0c6b }}/bplatform:${{ github.sha }}'